version: "2"
exclude_patterns:
- ruth/core/utils.py   # codeclimate has some encoding issues with this files because of emojis
checks:
  argument-count:
    config:
      threshold: 10
  file-lines:
    enabled: false
  method-count:
    enabled: false
