version: '3.0'

services:
  rasa:
    image: rasa/rasa:latest-full
    networks: ['ruth-network']
    ports:
    - "5005:5005"
    volumes:
    - "./ruth-app-data/:/app/"
    command:
    - run

  action_server:
    image: rasa/rasa-sdk:latest
    networks: ['ruth-network']
    ports:
    - "5055:5055"
    volumes:
    - "./ruth-app-data/actions:/app/actions"

  duckling:
    image: rasa/duckling:latest
    networks: ['ruth-network']
    ports:
    - "8000:8000"

networks: {rasa-network: {}}
